### PR TITLE
responsive header and content

### PR DESCRIPTION
**Pull request by JKHeadley**
This attempts to match the style and responsiveness of the original site while also adding some responsiveness to the main centent.

### CODE REVIEW

**Comment by JKHeadley** [comment]
@oormicreations when you get a chance, please do some quality/responsiveness testing on different screensizes/devices. You can review the code too if you like however you don't have too since there are many changes.

**Comment by oormicreations** [comment]
Hello @JKHeadley 
Looks excellent!
Everything is working fine, I noticed some minor things:
1 - The create your segment button is not there.
2 - The top header (with the logo on it) takes up 30% of the screen in landscape mode. On small screens, I checked it on my phone. Ideally it should not stick, it should scroll.
3 - The video titles are cutting off, they should stack below the thumbnails ideally (again on small screen phones).
I am attaching some screenshots.
Screenshot from 2021-03-24 02-53-56
Screenshot from 2021-03-24 02-56-16

**Comment by oormicreations** [comment]
@JKHeadley 
Titles are stacking now.

**Comment by JKHeadley** [comment]
> @JKHeadley
> Titles are stacking now.

@oormicreations thanks for checking :) I'm almost done fixing the header as well, hopefully will have it pushed by tomorrow/24 hrs.

**Comment by JKHeadley** [comment]
@oormicreations all done with the fixes, do you mind doing another review?

Also, I purposely removed the "create segment" button for now since the other site is not yet mobile friendly, so the experience would be confusing. Hopefully we can update the other site to be responsive soon and then we can add the button back.

**Comment by oormicreations** [comment]
@JKHeadley 
Yes, it is perfect.
Hopefully it will be linked with the old website soon. Its already a month now.
Lets merge.

**Review by oormicreations — COMMENTED** [review]
Perfect.

**Pull request merged**
